# Run parameters
print_console: false
solve_cplex: false
solve_heur: true
# Instances to read and solve (must be on single line)
instances_to_read: [d198]

# Instance generation
generate_instances: false
N_min: 100
N_incr: 5
N_max: 100

# Params for LK
# Max lenght of alternating path to search for
K: 400
# Max number of improving iterations (restarts)
I: 1000
# Max number of alternatives to look for when considering edges to add (0 means unbounded)
max_neighbours: 5
# Max depth (i) allowing trials of second choice for removing edge x_i
backtracking_threshold: 2
# Min lenght of the path to start intensification
intens_min_depth: 5
# Number of tours to consider for intensification
intens_n_tours: 50
# Number of random restarts
LK_iterations: 5

# TEST PARAMETERS
# Instances size to generate and solve in test script
size_to_test: [10, 20, 30, 40, 50, 60]
instances_per_size: 5
runs_per_instances: 10